export enum StatusCode {
    OK = 200,
    CREATED = 201,
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    TOO_MANY_REQUEST = 429,
    SERVER_ERROR = 500,
}

export enum ErrorCode {
    ALREADY_USED = "ALREADY_USED",
    WRONG_CREDENTIALS = "WRONG_CREDENTIALS",
}
