name: Web Build CI CD

on:
    push:
        branches: [dev]

jobs:
    generate-dist:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "22" # Specify your Node.js version

            - name: Install dependencies
              run: yarn install

            - name: Build the expo web app
              run: yarn web:build
